
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samuel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_administrador = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jd_agregarproductos = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jd_agregarclientes = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombree = new javax.swing.JTextField();
        tf_cuentaa = new javax.swing.JTextField();
        tf_identidad = new javax.swing.JTextField();
        tf_saldo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        jd_tabla = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jd_tabla1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_cuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_contrasena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("Administrador");

        jMenu3.setText("Productos");

        jMenuItem1.setText("Agregar Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Modificar Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Eliminar Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem7.setText("Listar Producto Tabla");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenu4.setText("Clientes");

        jMenuItem4.setText("Agregar Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Modificar Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Eliminar Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem8.setText("Listar Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jd_administrador.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_administradorLayout = new javax.swing.GroupLayout(jd_administrador.getContentPane());
        jd_administrador.getContentPane().setLayout(jd_administradorLayout);
        jd_administradorLayout.setHorizontalGroup(
            jd_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_administradorLayout.setVerticalGroup(
            jd_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jLabel4.setText("Nombre");

        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Productos");

        jLabel7.setText("Precio");

        jLabel8.setText("Fecha de caducidad");

        jButton2.setText("Agregar producto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarproductosLayout = new javax.swing.GroupLayout(jd_agregarproductos.getContentPane());
        jd_agregarproductos.getContentPane().setLayout(jd_agregarproductosLayout);
        jd_agregarproductosLayout.setHorizontalGroup(
            jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel6))
                    .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre)
                            .addComponent(tf_cantidad)
                            .addComponent(tf_precio)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarproductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        jd_agregarproductosLayout.setVerticalGroup(
            jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Clientes");

        jLabel10.setText("Nombre");

        jLabel11.setText("Cuenta");

        jLabel12.setText("Numero identidad");

        jLabel13.setText("Saldo disponible");

        jButton3.setText("Agregar Clientes");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel14.setText("Contrasena");

        javax.swing.GroupLayout jd_agregarclientesLayout = new javax.swing.GroupLayout(jd_agregarclientes.getContentPane());
        jd_agregarclientes.getContentPane().setLayout(jd_agregarclientesLayout);
        jd_agregarclientesLayout.setHorizontalGroup(
            jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarclientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(jd_agregarclientesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(34, 34, 34)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(tf_saldo)
                    .addComponent(tf_identidad)
                    .addComponent(tf_cuentaa)
                    .addComponent(tf_nombree)
                    .addComponent(tf_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jd_agregarclientesLayout.setVerticalGroup(
            jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarclientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(39, 39, 39)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_cuentaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34)
                .addGroup(jd_agregarclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cuenta", "Contrasena", "Identidad", "Saldo", "Productos"
            }
        ));
        jScrollPane2.setViewportView(tabla1);

        javax.swing.GroupLayout jd_tabla1Layout = new javax.swing.GroupLayout(jd_tabla1.getContentPane());
        jd_tabla1.getContentPane().setLayout(jd_tabla1Layout);
        jd_tabla1Layout.setHorizontalGroup(
            jd_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tabla1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jd_tabla1Layout.setVerticalGroup(
            jd_tabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tabla1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cuenta");

        tf_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cuentaActionPerformed(evt);
            }
        });

        jLabel2.setText("Contrasena");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("LogIn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_cuenta)
                    .addComponent(tf_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cuentaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if((tf_cuenta.getText().equals("erick123"))&&(tf_contrasena.getText().equals("321kcire"))){
            jd_administrador.pack();
            jd_administrador.setLocationRelativeTo(this);
            jd_administrador.setVisible(true);
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_agregarproductos.pack();
        jd_agregarproductos.setLocationRelativeTo(this);
        jd_agregarproductos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jd_agregarclientes.pack();
        jd_agregarclientes.setLocationRelativeTo(this);
        jd_agregarclientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         Dba db = new Dba("./basedatos.mdb");
         db.conectar();
         try {
             db.query.execute("INSERT INTO Productos (Nombre,Cantidad,Precio,Fecha)"
                    + " VALUES('"+tf_nombre.getText()+"', "+Integer.parseInt(tf_cantidad.getText())+
                     ", "+Double.parseDouble(tf_precio.getText())+", '"+date.getDate().toString()+"')");
            db.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
         db.desconectar();
       JOptionPane.showMessageDialog(jd_agregarproductos,"AGREGADO EXITOSO");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cantidad, Precio, Fecha from Productos");
            ResultSet rs = db.query.getResultSet();
            while(rs.next()){
                System.out.println(rs.getString(1)+"----->"+rs.getInt(2)+"----->"+rs.getDouble(3)+"---->"+rs.getString(4));
            }
        } catch (Exception e) {
        }
        db.desconectar();
        String mod = JOptionPane.showInputDialog("a)Nombre\n"
                + "b)Cantidad\n"
                + "c)Precio\n"
                + "d)Fecha");
        switch(mod){
            case "a":
                String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                String nombren = JOptionPane.showInputDialog("Ingrese el nombre que desea modificar: ");
                db.conectar();
                try {
                    db.query.execute("update Productos set nombre = '" + nombre + "'  where nombre = '"+nombren+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "b":
                String canti = JOptionPane.showInputDialog("Ingrese la cantidad: ");
                String canti1 = JOptionPane.showInputDialog("Ingrese la cantidad que desea modificar");
                int cantidad = Integer.parseInt(canti);
                int cantidad1 = Integer.parseInt(canti1);
                 db.conectar();
                try {
                    db.query.execute("update Productos set cantidad = '" + cantidad + "'  where cantidad = '"+cantidad1+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                
                break;
            case "c":
                String pr = JOptionPane.showInputDialog("Ingrese el precio: ");
                String pr1 = JOptionPane.showInputDialog("Ingrese el precio que desea modificar: ");
                double precio = Double.parseDouble(pr);
                double precion = Double.parseDouble(pr1);
                 db.conectar();
                try {
                    db.query.execute("update Productos set precio = '" + precio + "'  where precio = '"+precion+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "d":
                JOptionPane.showMessageDialog(jd_administrador,"EN MANTENIMIENTO :P");
                break;
        }
        db.desconectar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cantidad, Precio, Fecha from Productos");
            ResultSet rs = db.query.getResultSet();
            while(rs.next()){
                System.out.println(rs.getString(1)+"----->"+rs.getInt(2)+"----->"+rs.getDouble(3)+"---->"+rs.getString(4));
            }
        } catch (Exception e) {
        }
        db.desconectar();
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
        db.conectar();
        try {
            db.query.execute("delete from Productos where nombre = '" + nombre + "'");
            db.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        String nombre;
        int cantidad;
        double precio;
        String fecha;
        jd_tabla.pack();
        jd_tabla.setLocationRelativeTo(jd_administrador);
        jd_tabla.setVisible(true);
        Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cantidad, Precio, Fecha from Productos");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                nombre = rs.getString(1);
                cantidad = rs.getInt(2);
                precio = rs.getDouble(3);
                fecha = rs.getString(4);
                DefaultTableModel tab = (DefaultTableModel) tabla.getModel();
                tab.addRow(new Object[]{
                    nombre, cantidad, precio, fecha
                });
                
            }

        } catch (Exception e) {
        }
        db.desconectar();
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./basedatos.mdb");
         db.conectar();
         String pro = "";
         try {
             db.query.execute("INSERT INTO Clientes (Nombre,Cuenta,Contrasena,Identidad,Saldo,Productos)"
                    + " VALUES('"+tf_nombree.getText()+"', '"+tf_cuentaa.getText() + "', '" +tf_contra.getText()+
                     "', "+Integer.parseInt(tf_identidad.getText())+", "+Double.parseDouble(tf_saldo.getText())+ ", '" + pro +"')");
            db.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
         db.desconectar();
       JOptionPane.showMessageDialog(jd_agregarproductos,"AGREGADO EXITOSO");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
          Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cuenta, Contrasena, Identidad, Saldo, Productos from Clientes");
            ResultSet rs = db.query.getResultSet();
            while(rs.next()){
                System.out.println(rs.getString(1)+"----->"+rs.getString(2)+"----->"+rs.getString(3)+"---->"
                        +rs.getInt(4)+"---->"+rs.getDouble(5)+"---->"+rs.getString(6));
            }
        } catch (Exception e) {
        }
        db.desconectar();
        String mod = JOptionPane.showInputDialog("a)Nombre\n"
                + "b)Cuenta\n"
                + "c)Contrasena\n"
                + "d)Identidad\n"
                + "e)Saldo");
        switch(mod){
            case "a":
                String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                String nombren = JOptionPane.showInputDialog("Ingrese el nombre que desea modificar: ");
                db.conectar();
                try {
                    db.query.execute("update Clientes set nombre = '" + nombre + "'  where nombre = '" + nombren + "'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "b":
                String cuenta = JOptionPane.showInputDialog("Ingrese la cuenta : ");
                String cuentan = JOptionPane.showInputDialog("Ingrese la cuenta que desea modificar: ");
                db.conectar();
                try {
                    db.query.execute("update Clientes set cuenta = '" + cuenta + "'  where cuenta = '"+cuentan+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "c":
                String contra = JOptionPane.showInputDialog("Ingrese la contrasena: ");
                String contran = JOptionPane.showInputDialog("Ingrese la contrasena que desea modificar: ");
                db.conectar();
                try {
                    db.query.execute("update Clientes set contrasena = '" + contra + "'  where contrasena = '"+contran+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "d":
                String iden = JOptionPane.showInputDialog("Ingrese la identidad: ");
                String idenn = JOptionPane.showInputDialog("Ingrese la identidad que desea modificar: ");
                int identidad = Integer.parseInt(iden);
                int identidadn = Integer.parseInt(idenn);
                 db.conectar();
                try {
                    db.query.execute("update Clientes set identidad = '" + identidad + "'  where identidad = '"+identidadn+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
            case "e":
                String sal  = JOptionPane.showInputDialog("Ingrese el saldo: ");
                String saln = JOptionPane.showInputDialog("Ingrese el saldo que desea modificar: ");
                double saldo = Double.parseDouble(sal);
                double saldon = Double.parseDouble(saln);
                  db.conectar();
                try {
                    db.query.execute("update Clientes set saldo = '" + saldo + "'  where saldo = '"+saldon+"'");
                    db.commit();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();
                break;
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cuenta, Contrasena, Identidad, Saldo, Productos from Clientes");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                System.out.println(rs.getString(1) + "----->" + rs.getString(2) + "----->" + rs.getString(3) + "---->"
                        + rs.getInt(4) + "---->" + rs.getDouble(5) + "---->" + rs.getString(6));
            }
        } catch (Exception e) {
        }
        db.desconectar();
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
        db.conectar();
        try {
            db.query.execute("delete from Clientes where nombre = '" + nombre + "'");
            db.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        String nombre;
        String cuenta;
        String contrasena;
        int identidad;
        double saldo;
        String productos;
        jd_tabla1.pack();
        jd_tabla1.setLocationRelativeTo(jd_administrador);
        jd_tabla1.setVisible(true);
        Dba db = new Dba("./basedatos.mdb");
        db.conectar();
        try {
            db.query.execute("select Nombre, Cuenta, Contrasena, Identidad, Saldo, Productos from Clientes");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                nombre = rs.getString(1);
                cuenta = rs.getString(2);
                contrasena = rs.getString(3);
                identidad = rs.getInt(4);
                saldo = rs.getDouble(5);
                productos = rs.getString(6);
                DefaultTableModel tab = (DefaultTableModel) tabla1.getModel();
                tab.addRow(new Object[]{
                    nombre, cuenta, contrasena, identidad, saldo,productos
                });
                
            }

        } catch (Exception e) {
        }
        db.desconectar();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_administrador;
    private javax.swing.JDialog jd_agregarclientes;
    private javax.swing.JDialog jd_agregarproductos;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JDialog jd_tabla1;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_cuenta;
    private javax.swing.JTextField tf_cuentaa;
    private javax.swing.JTextField tf_identidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombree;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_saldo;
    // End of variables declaration//GEN-END:variables


}
